In [1]:
import numpy as np

In [2]:
array = np.array([1, 2, 3, 4, 5, 6])
array

array([1, 2, 3, 4, 5, 6])

In [3]:
arrays_divididos = np.split(array, 3)
arrays_divididos

[array([1, 2]), array([3, 4]), array([5, 6])]

In [4]:
for i, value in enumerate(arrays_divididos):
    print(f"Parte {i+1}: {value}")

Parte 1: [1 2]
Parte 2: [3 4]
Parte 3: [5 6]


In [5]:
#Criando um array 1D com temperaturas diárias de um mês (30 dias)
temperaturas = np.array([28, 19, 18, 29, 22, 21, 21, 
                         20, 29, 19, 28, 29, 
                         26, 19, 27, 24, 18, 
                         18, 19, 21, 21, 26, 
                         27, 18, 26, 21, 29, 
                         28, 29, 26, 16, 24])
temperaturas

array([28, 19, 18, 29, 22, 21, 21, 20, 29, 19, 28, 29, 26, 19, 27, 24, 18,
       18, 19, 21, 21, 26, 27, 18, 26, 21, 29, 28, 29, 26, 16, 24])

In [6]:
#Dividindo as temperaturas em 4 semanas
semanas = np.split(temperaturas, 4)
semanas

[array([28, 19, 18, 29, 22, 21, 21, 20]),
 array([29, 19, 28, 29, 26, 19, 27, 24]),
 array([18, 18, 19, 21, 21, 26, 27, 18]),
 array([26, 21, 29, 28, 29, 26, 16, 24])]

In [7]:
for i, value in enumerate(semanas):
    print(f"Semana {i+1}: {value}")

Semana 1: [28 19 18 29 22 21 21 20]
Semana 2: [29 19 28 29 26 19 27 24]
Semana 3: [18 18 19 21 21 26 27 18]
Semana 4: [26 21 29 28 29 26 16 24]


In [11]:
medias_semanas = [np.mean(semana) for semana in semanas]
medias_semanas

[np.float64(22.25), np.float64(25.125), np.float64(21.0), np.float64(24.875)]

In [12]:
for i, value in enumerate(medias_semanas):
    print(f"Média da semana {i+1}: {value:.2f}ºC")

Média da semana 1: 22.25ºC
Média da semana 2: 25.12ºC
Média da semana 3: 21.00ºC
Média da semana 4: 24.88ºC
